/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Algorithmes.RecuitSimule;

import java.awt.Component;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Corentin
 * Affiche une fenètre qui permet de lancer une solution de recuit simulé et affiche la carte correspondante (avec les lieux � montrer)
 */
public class Affichage extends javax.swing.JFrame {
	private JTextField jTextField5;
	/**
	 * Creates new form Affichage
	 */
	public Affichage() {
		try {
			initComponents();

			RecuitSimule simul = new RecuitSimule(10000, 1000, 0.99, 0.1, 10);
			simul.run();
			System.out.println("solution recuit fitness : "+simul.getMeilleurCout());

			CarteAffichage vue = new CarteAffichage();
			vue.initCarte(simul.getMeilleurSolutionConnue().getDispositionSimple(),this);
			vue.setBounds(0,0,1100,1100);

			this.add(vue);
			this.pack();
		} catch (IOException ex) {
			Logger.getLogger(Affichage.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		this.setTitle("Carte des agences et centres de formation");
		this.setDefaultCloseOperation(EXIT_ON_CLOSE);

		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jTextField1.setText("1000");
		jTextField1.setName("temperature"); // NOI18N
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jTextField2.setText("10000");
		jTextField2.setName("nbIt�rations"); // NOI18N

		jTextField3.setText("0.99");
		jTextField3.setName("mu"); // NOI18N

		jTextField4.setText("0.0");
		jTextField4.setName("epsilon"); // NOI18N
		
		jTextField5.setText("0.0");
		jTextField5.setName("cout : "); // NOI18N

		jLabel1.setText("Nb Iterations");
		jLabel1.setName("Temperature"); // NOI18N

		jLabel2.setText("Temperature");
		jLabel2.setName("Nombre d'iterations"); // NOI18N

		jLabel3.setText("Mu");
		jLabel3.setName("Mu"); // NOI18N

		jLabel4.setText("Epsilon");
		jLabel4.setName("Epsilon"); // NOI18N
		
		jButton1.setText("Lancer Recuit");
		jButton1.setName("Lancer Recuit"); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(661, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3)
								.addComponent(jLabel4)
								.addComponent(jLabel1)
								.addComponent(jLabel2)
								.addComponent(jButton1)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1)
						.addGap(2, 2, 2)
						.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(24, 24, 24)
						.addComponent(jLabel2)
						.addGap(14, 14, 14)
						.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(19, 19, 19)
						.addComponent(jLabel3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(25, 25, 25)
						.addComponent(jLabel4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(32, 32, 32)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(40, 40, 40)
						.addComponent(jButton1)
						.addContainerGap(351, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>                        

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here:
	}                                           

	//Lance un nouveau recuit simulé et r�initialise la carte
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {       

		try {
			initComponents();
			RecuitSimule simul = new RecuitSimule(Integer.parseInt(jTextField1.getText()), Double.valueOf(jTextField2.getText()),
					Double.valueOf(jTextField3.getText()),Double.valueOf(jTextField4.getText()),20);
			simul.run();
			System.out.println("solution recuit fitness : "+simul.getMeilleurCout());
			jTextField5.setText(String.valueOf(simul.getMeilleurCout()));

			CarteAffichage vue2 = new CarteAffichage();
			vue2.initCarte(simul.getMeilleurSolutionConnue().getDispositionSimple(),this);

			this.getContentPane().removeAll();
			vue2.setBounds(0,0,1100,1100);

			
			this.getContentPane().add(vue2);
			this.pack();
			this.revalidate();
			this.repaint();
		} catch (IOException ex) {
			Logger.getLogger(Affichage.class.getName()).log(Level.SEVERE, null, ex);
		}
	}                                                                               

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Affichage().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration                   
	RecuitSimule simul;
}



